# Copyright (C) 2016 Michel Müller, Tokyo Institute of Technology

# This file is part of Hybrid Fortran.

# Hybrid Fortran is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# Hybrid Fortran is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Lesser General Public License for more details.

# You should have received a copy of the GNU Lesser General Public License
# along with Hybrid Fortran. If not, see <http://www.gnu.org/licenses/>.

#***************************************************************************#
#  Makefile for Hybrid Fortran Build Interface                              #
#                                                                           #
#  Date             2013/03/04                                              #
#  Author           Michel Müller (TITECH)                                  #
#                                                                           #
#                                                                           #
# USUALLY NOTHING HERE SHOULD BE CHANGED!                                   #
# see the following files for changing build settings:                      #
#    * ./config/MakesettingsGeneral (directory settings,                    #
#                                      compilation exceptions )             #
#    * ./config/MakesettingsCPU (compiler settings CPU)                     #
#    * ./config/MakesettingsGPU (compiler settings GPU)                     #
#    * ./config/Makefile (source dependencies)                              #
#                                                                           #
#***************************************************************************#
TOOLSDIR=${HF_DIR}/hf_processor/
include ${TOOLSDIR}MakefileCommon
